### ISSUE TITLE
是否考虑将 node-sass 加入 peerDependencies 

### ISSUE THREAD

**Issue by nimoc** [fex-team/fis-parser-node-sass#22]
原因是我的构建工具是 fis + webpack 

如果 fis-parser-node-sass 和 sass-loader（webpack） 的 node-sass 都是 `peerDependencies`
我在自定义 node-sass 版本就能确保 fis 和 webpack 构建 的 css 绝对是一致的了。

---

**补充一下我的使用场景：**  
js 部分构建我都用 webpack ，要内嵌 js 的 sass 我也用 webpack。不需要内嵌 js 的 sass 我用 fis 编译。最后会利用 fis 的文件指纹生成 map.json 做静态资源管理。

**Comment by 2betop** [comment]
可以试试这个 https://github.com/fex-team/fis3-preprocessor-js-require-css

**Comment by nimoc** [comment]
@2betop 
使用webpack 的原因是 npm 生态和纯前端打包不费心。js 部分就全部交给 webpack 了，只需要 fis 对js 文件进行hash入表处理。
