### ISSUE TITLE
install问题

### ISSUE THREAD

**Issue by jiajianrong** [fex-team/fis-parser-node-sass#26]
32位/64位问题？还是因为我机子里缺python啊？
》》》我电脑是64位win7，node是v0.12.3
多谢

> node-sass@3.7.0 postinstall C:\Users\58\AppData\Roaming\npm\node_modules\jr8\n
> ode_modules\fis-parser-node-sass\node_modules\node-sass
> node scripts/build.js

"C:\Users\58\AppData\Roaming\npm\node_modules\jr8\node_modules\fis-parser-node-s
ass\node_modules\node-sass\vendor\win32-x64-14\binding.node" exists.
 testing binary.
Problem with the binary:
Error: %1 is not a valid Win32 application.
C:\Users\58\AppData\Roaming\npm\node_modules\jr8\node_modules\fis-parser-node-sa
ss\node_modules\node-sass\vendor\win32-x64-14\binding.node
Manual build incoming.
Building: C:\Program Files\nodejs\node.exe C:\Users\58\AppData\Roaming\npm\node_
modules\jr8\node_modules\fis-parser-node-sass\node_modules\node-sass\node_module
s\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --
libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\Program Files\nodejs\node.exe',
gyp verb cli   'C:\Users\58\AppData\Roaming\npm\node_modules\jr8\node_mo
dules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\bi
n\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.3.1
gyp info using node@0.12.3 | win32 | x64
 rebuild []ommand
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\58\AppData\Roaming\npm
\node_modules\jr8\node_modules\fis-parser-node-sass\node_modules\node-sass\node_
modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\58\AppData\Roaming\npm\node_modules\j
r8\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gy
p\node_modules\which\which.js:69:19)
`which` failed     at E (C:\Users\58\AppData\Roaming\npm\node_modules\jr8\node_m
odules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_mo
dules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\jr8\

gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\58\AppData\Roaming\npm
\node_modules\jr8\node_modules\fis-parser-node-sass\node_modules\node-sass\node_
modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\58\AppData\Roaming\npm\node_modules\j
r8\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gy
p\node_modules\which\which.js:69:19)
`which` failed     at E (C:\Users\58\AppData\Roaming\npm\node_modules\jr8\node_m
odules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_mo
dules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\jr8\
node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\n
ode_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\jr8\
node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\n
ode_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\jr8\
node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\n
ode_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:95:15)
gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\58\AppData\Roaming\npm
\node_modules\jr8\node_modules\fis-parser-node-sass\node_modules\node-sass\node_
modules\node-gyp\node_modules\which\which.js:14:12)
gyp verb `which` failed     at F (C:\Users\58\AppData\Roaming\npm\node_modules\j
r8\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gy
p\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\58\AppData\Roaming\npm\node_modules\j
r8\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gy
p\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\jr8\
node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\n
ode_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\jr8\
node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\n
ode_modules\which\node_modules\isexe\index.js:44:5
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\jr8\
node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\n
ode_modules\which\node_modules\isexe\windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:95:15)
gyp verb `which` failed  python { [Error: not found: python] code: 'ENOENT' }
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\58\AppData\Roaming\npm\node_modules
\jr8\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-
gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\58\AppData\Roaming\npm\node_modules\jr8\node_modu
les\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\lib\config
ure.js:356:11
stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\58\AppData\
Roaming\npm\node_modules\jr8\node_modules\fis-parser-node-sass\node_module
s\node-sass\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--verbose" "-
-libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\58\AppData\Roaming\npm\node_modules\jr8\node_modules\fis-p
arser-node-sass\node_modules\node-sass
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v3.3.1

gyp ERR! not ok
Build failed
npm WARN optional dep failed, continuing fsevents@0.3.8
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs
\node_modules\npm\bin\npm-cli.js" "--registry" "http://registry.cnpmjs.org"
"install" "-g" "jr8"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.7.0 postinstall script 'node scripts/build.js
'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\58\npm-debug.log

**Comment by 2betop** [comment]
升级下 node 试试？

**Comment by jiajianrong** [comment]
我用的fis2
最多升到v4啊

不知道fis-parser-node-sass对node版本有没有要求？我试试吧

**Comment by jiajianrong** [comment]
0.12.7应该没问题了
