### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by MarvinXu** [fex-team/fis-parser-node-sass#30]
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolch
ain, use it instead!
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a
 RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid
a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid
a RegExp DoS issue
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash
@^3.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a
 RegExp DoS issue
/

> node-sass@3.7.0 install C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node-sas
> s\node_modules\node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.7.0/win32-ia32-14_
binding.node":

connect ETIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

```
  export HTTP_PROXY=http://example.com:1234
```

or configure npm proxy via

```
  npm config set proxy http://example.com:8080
```

> node-sass@3.7.0 postinstall C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node
> -sass\node_modules\node-sass
> node scripts/build.js

Building: D:\Program Files (x86)\nodejs\node.exe C:\Users\58\AppData\Roaming\npm\node_modu
les\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebu
ild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'D:\Program Files (x86)\nodejs\node.exe',
gyp verb cli   'C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node-sass\
node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.3.1
gyp info using node@0.12.7 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\58\AppData\Roaming\npm\node_modu
les\fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\w
hich.js:14:12)
gyp verb `which` failed     at F (C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-
node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:69:19)
gyp verb `which` failed     at E (C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-
node-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:81:29)
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-nod
e-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\which.js:90:16
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-nod
e-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\
index.js:44:5
gyp verb `which` failed     at C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-nod
e-sass\node_modules\node-sass\node_modules\node-gyp\node_modules\which\node_modules\isexe\
windows.js:29:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:95:15)
gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import platform; print(platform.
python_version());"` returned: "2.7.11\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 0.
12.7
gyp verb command install [ '0.12.7' ]
gyp verb install input version string "0.12.7"
gyp verb install installing version: 0.12.7
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 0.12.7
gyp verb build dir attempting to create "build" dir: C:\Users\58\AppData\Roaming\npm\node_
modules\fis-parser-node-sass\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\Users\58\AppData\Roaming\npm\node_
modules\fis-parser-node-sass\node_modules\node-sass\build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\Users\58\AppData\Roaming\npm\node_m
odules\fis-parser-node-sass\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\Users\58\AppData\Roaming\npm\node_modules\
fis-parser-node-sass\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\Users\58\AppData\Roaming\npm\node_modules\
fis-parser-node-sass\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node
-sass\node_modules\node-sass\node_modules\node-gyp\gyp\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node
-sass\node_modules\node-sass\build\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node
-sass\node_modules\node-sass\node_modules\node-gyp\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\Users\58\.node-gyp\0.12.7\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\Users\58\.node-gyp\0.12.7',
gyp info spawn args   '-Dnode_gyp_dir=C:\Users\58\AppData\Roaming\npm\node_modules\
fis-parser-node-sass\node_modules\node-sass\node_modules\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\Users\58\AppData\Roaming\npm\node_module
s\fis-parser-node-sass\node_modules\node-sass',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node
-sass\node_modules\node-sass\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ia32
gyp verb node dev dir C:\Users\58.node-gyp\0.12.7
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? null
gyp verb copying "node.lib" for ia32 C:\Users\58.node-gyp\0.12.7\Release\node.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
生成启动时间为 2016/6/22 20:47:43。
节点 1 上的项目“C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_mo
dules\
node-sass\build\binding.sln”(默认目标)。
ValidateSolutionConfiguration:
  正在生成解决方案配置“Release|Win32”。
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .N
ET Framework 2.0
SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了其他位置，请将其位置
添加到系统路径中。 [C:\Users\58\Ap
pData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\build\binding.
sln]
已完成生成项目“C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_mod
ules\no
de-sass\build\binding.sln”(默认目标)的操作 - 失败。

生成失败。

“C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass

\build\binding.sln”(默认目标) (1) ->
(_src_\libsass 目标) ->
  MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装
.NET Framework 2.
0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了其他位置，请将其位
置添加到系统路径中。 [C:\Users\58\
AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\build\bindin
g.sln]

```
0 个警告
1 个错误
```

已用时间 00:00:00.12
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed w
ith exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\58\AppData\Roaming\npm\node_modules\fi
s-parser-node-sass\node_modules\node-sass\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\Program Files (x86)\nodejs\node.exe" "C:\Users\58\AppData\Roam
ing\npm\node_modules\fis-parser-node-sass\node_modules\node-sass\node_modules\node-
gyp\bin\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsa
ss_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\58\AppData\Roaming\npm\node_modules\fis-parser-node-sass\node_module
s\node-sass
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\Program Files (x86)\nodejs\\node.exe" "D:\Program Files (x86)\node
js\node_modules\npm\bin\npm-cli.js" "install" "fis-parser-node-sass" "-g"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.7.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.7.0 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\git\demo-lv1\npm-debug.log

**Comment by 2betop** [comment]
注意这句

```
Cannot download "https://github.com/sass/node-sass/releases/download/v3.7.0/win32-ia32-14_
binding.node":
```

一定是被墙了，用 cnpm 安装吧。

**Comment by MarvinXu** [comment]
我的node是0.12.7的，不支持cnpm :(
