### ISSUE TITLE
mac下编译报错

### ISSUE THREAD

**Issue by mewtwoNeo** [fex-team/fis-parser-node-sass#32]
[ERROR] load plugin [fis-parser-node-sass] config error : Error: The `libsass` binding was not found in /Users/mewtwo/work/workspace/discovery/fis-vuejs-seed/node_modules/fis-parser-node-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node

This usually happens because your node version has changed.

这个插件对node版本是有要求吗？依赖什么版本的node的啊

**Comment by 2betop** [comment]
node-sass 没安装成功，或者是你之前安装的版本，再你更换 node 环境后失效了。
