### ISSUE TITLE
Mac系统使用问题及解决

### ISSUE THREAD

**Issue by lidianhao123** [fex-team/fis-parser-node-sass#41]
**描述：**
> 系统： OS X EI Caption 10.11.6
> node:  V6.9.2
> FIS3

**命令**
```shell
$ sudo npm fis-parser-node-sass -g
$ fis3 release debug -wL
 [ERROR] ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/fis-parser-node-sass/node_modules/node-sass/vendor'
```
**解决方案**
后来在 NPM 官网查到 [fis3-parser-node-sass](https://www.npmjs.com/package/fis3-parser-node-sass) 安装之后可以正常使用。

*希望 FIS 官方可以进行说明或者更新包的描述*

**Comment by a526672351** [comment]
这个问题还没有解决吗？
