### ISSUE TITLE
node-sass路径匹配问题

### ISSUE THREAD

**Issue by joyz0** [fex-team/fis-parser-node-sass#46]
```javascript
fis.match('/**.scss', {
    rExt: '.css',
    parser: fis.plugin('node-sass', {
        include_paths: [
            '/static/scss'
        ]
    })
});
```
请问'/**.scss'和 '/static/scss'以哪个为准？

**Comment by Justable** [comment]
fis.match('/({page,static}/**.scss)', {
    rExt: '.css',
    parser: fis.plugin('node-sass', {
        include_paths: [
            '/({page,static}/**.scss)'
        ]
    })
});
fis3 inspect之后
~ /widget/footer/footer.scss
 -- parser [plugin `node-sass`] `*.{sass,scss}`   (1th)
 -- rExt .css `*.{sass,scss}`   (1th)
 -- release /static/widget/footer/footer.css `**`   (4th)
-------------------------------------------------------
fis.match('/({page,static,widget}/**.scss)', {
    rExt: '.css',
    parser: fis.plugin('node-sass', {
        include_paths: [
            '/({page,static,widget}/**.scss)'
        ]
    })
});
fis3 inspect之后
 ~ /widget/footer/footer.scss
 -- parser [plugin `node-sass`] `/({page,static,widget}/**.scss)`   (18th)
 -- rExt .css `/({page,static,widget}/**.scss)`   (18th)
 -- release /static/widget/footer/footer.css `**`   (4th)
我有点搞不明白了，是jello的默认设置使然？

**Comment by Justable** [comment]
> 路径匹配和我预期不符

fis3 inspect之后
`~ /widget/footer/footer.scss
 -- parser [plugin `node-sass`] `*.{sass,scss}`   (1th)
 -- rExt .css `*.{sass,scss}`   (1th)
 -- release /static/widget/footer/footer.css `**`   (4th)`

-------------------------------------------------------
`fis.match('/({page,static,widget}/**.scss)', {
    rExt: '.css',
    parser: fis.plugin('node-sass', {
        include_paths: [
            '/({page,static,widget}/**.scss)'
        ]
    })
});`
fis3 inspect之后
` ~ /widget/footer/footer.scss
 -- parser [plugin `node-sass`] `/({page,static,widget}/**.scss)`   (18th)
 -- rExt .css `/({page,static,widget}/**.scss)`   (18th)
 -- release /static/widget/footer/footer.css `**`   (4th)`
我有点搞不明白了，是jello的默认设置使然？

**Comment by joyz0** [comment]
> 路径匹配和预期不符，是jello的默认配置导致吗

```javascript
fis.match('/({page,static}/**.scss)', {
        rExt: '.css',
        parser: fis.plugin('node-sass', {
            include_paths: [
                '/({page,static}/**.scss)'
            ]
        })
    });
```
fis3 inspect之后
```javascript
 ~ /widget/footer/footer.scss
 -- parser [plugin `node-sass`] `*.{sass,scss}`   (1th)
 -- rExt .css `*.{sass,scss}`   (1th)  //这里不应该是/({page,static}/**.scss)这样才对吗
 -- release /static/widget/footer/footer.css `**`   (4th)
```

```javascript
fis.match('/({page,static,widget}/**.scss)', {
    rExt: '.css',
    parser: fis.plugin('node-sass', {
        include_paths: [
            '/({page,static,widget}/**.scss)'
        ]
    })
});
```
fis3 inspect之后
```javascript
 ~ /widget/footer/footer.scss
 -- parser [plugin `node-sass`] `/({page,static,widget}/**.scss)`   (18th)
 -- rExt .css `/({page,static,widget}/**.scss)`   (18th) //这里就和预期相符了
 -- release /static/widget/footer/footer.css `**`   (4th)
```
