### ISSUE TITLE
求助,由于变量, mixin分别定义在不同的文件中,release的时候会报变量无法解析或找不到mixin的错误

### ISSUE THREAD

**Issue by Julienedies** [fex-team/fis-parser-node-sass#5]
我做了一个简单的demo,说明这种情况,

[https://github.com/Julienedies/fis-sass-demo](https://github.com/Julienedies/fis-sass-demo)

```
 [ERROR] parser.sass: no mixin named transition
Backtrace:
        ../../..//static/extend/ionic/scss/_action-sheet.scss:7 [`/static/extend/ionic/scss/_action-sheet.scss` 7:12] [D:/test/fis-sass/static/extend/ionic/scss/_action-sheet.scss]
```

**Comment by 2betop** [comment]
明明少了个 `s`

**Comment by 2betop** [comment]
不对啊，_action-sheet.scss 这个文件，你既然要用 mixin `transition` 你怎么不 import 进来？

**Comment by Julienedies** [comment]
大部分前端类库都是这样写sass的, 比如bootstrap-sass,我觉得这种场景应该很多的,我想知道有没有简单的方法去处理这种情况.

在每一个文件里手动import,这种可以解决问题,但感觉非常不友好.

**Comment by Julienedies** [comment]
[http://www.orrafy.com/posts/fisbook/use-bootstrap-scss-in-fis/](http://www.orrafy.com/posts/fisbook/use-bootstrap-scss-in-fis/)
这里有一个类似的情况, 可惜我照做下来是错误的.

**Comment by 2betop** [comment]
搞了半天是你的正则写错了。

```
//部署配置
fis.config.set('roadmap.path', [
    //以_开头的文件，不发布
    {
        reg: /.*\/_.+\.(?:scss)/i,
        release:false
    }
]);
```

你的意图应该是 _ 打头的文件不独立编译，可是你之前的正则是没要匹配到这个文件的 `static/extend/ionic/scss/_action-sheet.scss:`

**Comment by Julienedies** [comment]
恩，谢谢， 我试下

**Comment by Julienedies** [comment]
@2betop ，惭愧，真的是这个原因，已解决，非常感谢！
