### ISSUE TITLE
npm i -g fis-parser-node-sass 出错

### ISSUE THREAD

**Issue by mcattx** [fex-team/fis-parser-node-sass#9]
我的 `Node` 版本是 `0.12.2`， `npm` 版本是 `2.7.4`。在 windows7 64位系统安装 `fis-parser-node-sass` ，得到以下报错。

![6](https://cloud.githubusercontent.com/assets/3294102/11706739/89adb3da-9f36-11e5-9a20-cc9fcaac25b7.png)

![5](https://cloud.githubusercontent.com/assets/3294102/11706745/9aaddc5a-9f36-11e5-9e44-41be58de3115.png)

![4](https://cloud.githubusercontent.com/assets/3294102/11706698/101ee12e-9f36-11e5-8780-d2da39d810ba.png)

**Comment by zhangtao07** [comment]
cnpm 安装试试
